version: "3"
services:
    admindashbase:
        container_name: $CONTAINER_NAME
        environment:
            APP_ENV: $APP_ENV
            APP_NAME: $APP_NAME
            VERSION: $CI_COMMIT_SHORT_SHA
            PORT: $PORT
            DB_CONN_STRINGS: $DB_CONN_STRINGS
            JWT_PUB_KEY: $JWT_PUB_KEY
            TOTP_SECRET: $TOTP_SECRET
            CONTAINER_NAME: $CONTAINER_NAME
            BASE_URLS: $BASE_URLS
            SLACK_TOKEN: $SLACK_TOKEN
            CHANNEL_ID: $CHANNEL_ID
            MEILI_CONFIG: $MEILI_CONFIG
            INDEX_MODIFIERS: $INDEX_MODIFIERS
            TXN_TYPE_MAP: $TXN_TYPE_MAP
            BIZ_ACCOUNT_MAP: $BIZ_ACCOUNT_MAP
            VENTOGRAM_ACCOUNT_MAP: $VENTOGRAM_ACCOUNT_MAP
            CURRENCY_MAP: $CURRENCY_MAP
            FORMAT_FIELD_NAMES: $FORMAT_FIELD_NAMES
            BIZ_TXN_MAP: $BIZ_TXN_MAP
            VENTOGRAM_TRANSACTION_MAP: $VENTOGRAM_TRANSACTION_MAP
            FUSION_AUTH_BASE_URL: $FUSION_AUTH_BASE_URL
            FUSION_AUTH_ADMIN_API_KEY: $FUSION_AUTH_ADMIN_API_KEY
            FUSION_AUTH_ADMIN_TENANT_ID: $FUSION_AUTH_ADMIN_TENANT_ID
            FUSION_AUTH_ADMIN_APPLICATION_ID: $FUSION_AUTH_ADMIN_APPLICATION_ID
            FUSION_AUTH_COINPROFILE_API_KEY: $FUSION_AUTH_COINPROFILE_API_KEY
            FUSION_AUTH_COINPROFILE_TENANT_ID: $FUSION_AUTH_COINPROFILE_TENANT_ID
            FUSION_AUTH_COINPROFILE_APPLICATION_ID: $FUSION_AUTH_COINPROFILE_APPLICATION_ID
            BYBIT_CONFIG: $BYBIT_CONFIG


        expose:
            - $PORT
        ports:
            - "$PORT"
        restart: unless-stopped
