version: "3"
services:
    admindashbase:
        container_name: ${{ secrets.CONTAINER_NAME }}
        environment:
            APP_ENV: ${{ secrets.APP_ENV }}
            APP_NAME: ${{ secrets.APP_NAME }}
            VERSION: ${{ github.sha }}
            PORT: ${{ secrets.PORT }}
            DB_CONN_STRINGS: ${{ secrets.DB_CONN_STRINGS }}
            JWT_PUB_KEY: ${{ secrets.JWT_PUB_KEY }}
            TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
            CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
            BASE_URLS: ${{ secrets.BASE_URLS }}
            SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
            CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
            MEILI_CONFIG: ${{ secrets.MEILI_CONFIG }}
            INDEX_MODIFIERS: ${{ secrets.INDEX_MODIFIERS }}
            TXN_TYPE_MAP: ${{ secrets.TXN_TYPE_MAP }}
            BIZ_ACCOUNT_MAP: ${{ secrets.BIZ_ACCOUNT_MAP }}
            VENTOGRAM_ACCOUNT_MAP: ${{ secrets.VENTOGRAM_ACCOUNT_MAP }}
            CURRENCY_MAP: ${{ secrets.CURRENCY_MAP }}
            FORMAT_FIELD_NAMES: ${{ secrets.FORMAT_FIELD_NAMES }}
            BIZ_TXN_MAP: ${{ secrets.BIZ_TXN_MAP }}
            VENTOGRAM_TRANSACTION_MAP: ${{ secrets.VENTOGRAM_TRANSACTION_MAP }}
            FUSION_AUTH_BASE_URL: ${{ secrets.FUSION_AUTH_BASE_URL }}
            FUSION_AUTH_ADMIN_API_KEY: ${{ secrets.FUSION_AUTH_ADMIN_API_KEY }}
            FUSION_AUTH_ADMIN_TENANT_ID: ${{ secrets.FUSION_AUTH_ADMIN_TENANT_ID }}
            FUSION_AUTH_ADMIN_APPLICATION_ID: ${{ secrets.FUSION_AUTH_ADMIN_APPLICATION_ID }}
            FUSION_AUTH_COINPROFILE_API_KEY: ${{ secrets.FUSION_AUTH_COINPROFILE_API_KEY }}
            FUSION_AUTH_COINPROFILE_TENANT_ID: ${{ secrets.FUSION_AUTH_COINPROFILE_TENANT_ID }}
            FUSION_AUTH_COINPROFILE_APPLICATION_ID: ${{ secrets.FUSION_AUTH_COINPROFILE_APPLICATION_ID }}
            # BYBIT_CONFIG: ${{ secrets.BYBIT_CONFIG }}
            

        expose:
            - $PORT
        ports:
            - ${{ secrets.PORT }}
        restart: unless-stopped
